version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule: {interval: weekly}
    groups:
      ci-python-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
    groups:
      release-actions:
        patterns: ["*"]
